import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/json-ld";
import { formatTokenCount } from "@/lib/format";
import { getCertificate } from "@/lib/repository";
import { getRuntimeEnv, siteUrl } from "@/lib/runtime";
import { verifyPayload } from "@/lib/crypto";
import { getLocale } from "@/lib/i18n-server";
import { languageAlternates } from "@/lib/i18n";

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const locale = await getLocale(); const { id } = await params; const cert = await getCertificate(id); if (!cert || (cert.status === "active" && !cert.indexable)) return { title: locale === "zh" ? "私密证书" : "Private certificate", robots: { index: false, follow: false } }; return { title: `${cert.displayName} · ${formatTokenCount(cert.processedTokens)} ${locale === "zh" ? "Token 证书" : "Token Certificate"}`, description: locale === "zh" ? `${cert.period} 的 LovTokens 证书 ${cert.id}。` : `LovTokens certificate ${cert.id} for ${cert.period}.`, alternates: languageAlternates(`/certificate/${cert.id}`, locale) }; }
export default async function CertificatePage({ params }: { params: Promise<{ id: string }> }) {
  const locale = await getLocale();
  const { id } = await params; const c = await getCertificate(id); if (!c || (c.status === "active" && !c.indexable)) notFound(); const revoked = c.status !== "active"; const env = await getRuntimeEnv(); const proof = await verifyPayload(c.payloadJson, c.payloadHash, c.signature, env.CERTIFICATE_PRIVATE_JWK);
  return <section className="certificate-page"><div className={`certificate ${revoked ? "certificate-revoked" : ""}`}><div className="certificate-lines" /><div className="certificate-top"><strong>{locale === "zh" ? "LOVTOKENS / 使用量证书" : "LOVTOKENS / USAGE CERTIFICATE"}</strong><span>{locale === "zh" ? "编号" : "NO."} {c.id.toUpperCase()}</span></div><div className="certificate-body"><small>{c.kind.toUpperCase()} · {c.period}</small><h1>{revoked ? (locale === "zh" ? "身份已撤回" : "Identity withdrawn") : c.displayName}</h1><strong>{formatTokenCount(c.processedTokens)}</strong><p>{locale === "zh" ? "由 LovTokens 采集器统计的汇总输入 + 输出 Token" : "aggregate input + output tokens measured by the LovTokens collector"}</p><div className="certificate-seal"><strong>{proof.replaceAll("-", " ")}</strong><span>{c.coverage.toFixed(0)}% {locale === "zh" ? "覆盖率" : "COVERAGE"}</span></div></div><div className="certificate-foot"><span>{locale === "zh" ? "签发日期" : "ISSUED"}<br />{new Date(c.issuedAt * 1000).toISOString().slice(0, 10)}</span><span>{locale === "zh" ? "排名 / 信任" : "RANK / TRUST"}<br />{c.rank ? `#${c.rank} · ` : ""}{c.trustLevel.replaceAll("-", " ")}</span><span>PAYLOAD SHA-256<br />{c.payloadHash}</span></div></div><div className="shell" style={{ color: "#aeb5ac", maxWidth: 1200, paddingTop: 25 }}><p>{locale === "zh" ? "此证书通过密码学方式保护冻结的汇总数据。它是 LovTokens 提供的独立证明，并非 OpenAI 或 Anthropic 认证。" : "This certificate cryptographically protects its frozen aggregate payload. It is independent evidence from LovTokens, not an OpenAI or Anthropic certification."}</p></div><JsonLd data={{ "@context": "https://schema.org", "@type": "CreativeWork", name: `LovTokens Token Certificate ${c.id}`, url: `${siteUrl()}/certificate/${c.id}`, dateCreated: new Date(c.issuedAt * 1000).toISOString(), identifier: c.id }} /></section>;
}
